---
title: Ex.1 Parsing Protein Structures
format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    code-fold: true
    number-sections: true
Authors: "Marta Aransay, Carlota de la Concepción, Marta Rodrigo, Lucía Santos"
crossref:
  lst-title: "Function"
  lst-prefix: "Function"
date: 04/03/2026
---

# Introduction

Proteins are macromolecules whose function is highly related to their three-dimensional structure. Their organization can be described in four levels, which depend on folding. Protein folding is driven by non-covalent intramolecular interactions between residues of the same polypeptide chain, whereas intermolecular interactions contribute to quaternary structure formation. These interactions include hydrogen bonds, hydrophobic interactions and electrostatic forces. Structural bioinformatics aims to characterize these interactions through computational analysis of experimentally determined or predicted structures.

The main repository of experimentally determined macromolecuar structures is the Protein Data Bank (PDB), which stores three-dimensional structures obtained by X-ray crystallography, nuclear magnetic resonance spectroscopy and cryo-electron microscopy. PDB files contain detailed metadata, experimental information, protein sequences, and three-dimensional atomic coordinates. Through computational analysis, this information can be extracted from these files.

To analyze protein architecture contact maps are commonly used as a simplified representation of the three-dimensional structure. These maps use pairwise distance matrices to provide a two-dimensional visualization of the interactions between the Cα atoms of residues within a protein or between different protein chains. In addition, specific patterns are associated with specific secondary structure elements, so it is possible to infer the spatial organization of proteins.

Nowadays, although modelling and structure prediction methods have achieved high levels of accuracy, the analysis of atomic coordinates is still essential to understand the spatial organization of proteins and macromolecular complexes.


## Objective

The main objective of this project is to implement computational functions to:

1. Parse PDB files to extract structural metadata and atomic coordinates.
2. Compute pairwise distance matrices between Cα atoms of protein residues.
3. Plot contact maps to characterize the structural organization and oligomeric state of the analyzed proteins.

---

# Methods

## Data Collection

RCSB-PDB (Research Collaboratory for Structural Bioinformatics Protein Data Bank, https://www.rcsb.org/) is a repository of experimentally determined, and also computationally predicted, structures of proteins, nucleic acids and macromolecular complexes. 

Each protein in this database is identified with a unique four-character alphanumeric identifier. This identifier allows access to detailed information about the protein, such as atomic coordinates, sequence, experimental methodology and associated metadata.

The structures analyzed in this project correspond to the following proteins:

- **Plasma Retinol-Binding Protein Precursor (*Homo sapiens*, PDB ID: 1RBP)**, which is involved in retinol transport in humans.
- **Carbonic Anhydrase (*Methanosarcina thermophila*, PDB ID: 1QRE)**, which regulates pH by catalyzing the reaction between $CO_2$ and $H_2O$ to produce bicarbonate and protons.
- **Catalase (*Homo sapiens*, PDB ID: 1DGF)**, which protect cells from oxidative damage by decomposing $H_2O_2$ into water and oxygen.

## Parsing PDB Files

::: {.callout-note}
 Before introducing the main functions of the project, it is important to highlight the implmentation of @lst-setup-libraries, which initializes all required libraries and dependencies, avoiding redundancy and improving code readability.  
:::

The data base PDB is one of the most widely used worldwide in the field of bioinformatics, among other aspects for its accessibility and the large amount of information it contains. Taking advantage of the possibility of querying through its API, we have been able to extract the necessary data through a parsing function @lst-get-metadata.

The objective of this function is to parse the PDB files of the studied proteins, extracting the relevant information for subsequent analysis. Specifically, we have obtained the descriptive and experimental information associated with each entry of the Protein Data Bank.

The function defined as @lst-get-metadata performs two independent queries to the RCSB PDB REST API (https://data.rcsb.org/redoc/index.html), one at the structural level (https://data.rcsb.org/redoc/index.html#tag/Entry-Service/operation/getEntryById) and another at the polymer entity level (https://data.rcsb.org/redoc/index.html#tag/Entity-Service/operation/getPolymerEntityById). This separation allows us to access both the experimental and general details of the protein and the specific information related to it. 

In first place, the function implements a basic system of error handling to ensure that the queries are successful. This is approached through the definition of the function @lst-api-errors, which checks the status code of the response and returns an appropriate message in case of an error. 

Once the queries are successful, the function extracts the relevant information from the JSON responses:

```{python}
#| echo: false

import pandas as pd

table_info = pd.DataFrame({
    "Metadata": ["PDB ID", "Protein Name", "Source Organism", "Determination Method", "Authors", "Release Date", "Resolution", "Number of Peptide Chains", "Number of Other Molecules"],
    "Description": ["Unique identifier for the protein structure", "The name of the protein", "The organism from which the protein was derived", "The method used to determine the protein structure (e.g., X-ray crystallography, NMR spectroscopy)", "The researchers who contributed to the determination of the structure", "The release date of the structure", "The resolution of the structure, if applicable", "The number of peptide chains present in the structure", "The number of other molecules (e.g., ligands, water) present in the structure"],
    "Source (API JSON field)": ["rcsb_id", "rcsb_polymer_entity.pdbx_description", "rcsb_entity_source_organism", "exptl.method", "rcsb_authors", "rcsb_accession_info.initial_release_date", "rcsb_entry_info.resolution_combined", "rcsb_entry_info.polymer_entity_count_protein", "rcsb_entry_info.nonpolymer_entity_count"]
})

table_info

```

There are also some fields with multiple values, such as authors, experimental methods, etc. For those cases, an auxiliary function (@lst-extract-metadata) is used to concatenate the elements of the list into a single string, separating the values with commas. This facilitates the presentation of the information and its subsequent analysis.

All this information is organized into a structured fromat, as it is a dictionary, which allows its conversion into a pandas DataFrame and its export to a CSV file for further analysis and visualization. This is done through the @lst-get-metadata, which takes the metadata dictionary and the desired file name as input and saves the DataFrame as a CSV file. 

### Code Implementation

```{python}
#| label: lst-setup-libraries
#| lst-cap: "Set up necessary libraries."
#| message: false
#| warning: false
#| code-fold: true
#| code-summary: "Click to see imported libraries."

import requests
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches 

```

```{python}
#| label: lst-api-errors
#| lst-cap: "Function for handling HTTP request errors."
#| code-fold: true
#| code-summary: "Click to see handle_API_error function."

def handle_API_error(id, status_code = None, flag_timeout = False):
    """
    Handles HTTP request errors or timeouts and prints informative messages in
    order to centralize the management of API request errors.

    Parameters
    ----------
    id : str
        PDB ID queried in the request.
    status_code : int
        HTTP status code returned by the request. 
        None by default (in case of timeout error).
    flag_timeout : bool
        Indicates whether the request failed due to a timeout.
        If True, the status_code is ignored.
        alse by default.

    Returns
    -------
        bool (True)
            True if the request was successful (status code 200).
            None returned for any error or timeout condition.
    """
    if flag_timeout: # If a timeout occurred, skip all other checks
        print(f"[408] Timeout error for ID: {id}.")
        
    else:
        if status_code == 200: # If the request was successful, returns True
            return True
        
        elif status_code == 301 or status_code == 302:
            # Resource has been permanently or temporarily moved
            print(f"[301] or [302] The object was moved to other route")

        elif status_code == 400:
            # Request processed but considered unsuccessful
            print(f"[400] Not valid ID: {id}")

        elif status_code == 404:
            # Request processed but no result was obtained
            print(f"[404] Result not found for ID: {id}")

        elif status_code == 429:
            # Request rejected due to request rate limits
            print(f"[429] Error: Too many requests.")

        elif status_code == 500 or status_code == 503:
            # Request failed due to internal server issues
            print("[500] or [503] Internal Server Error")

        else: # For any other error status code
            print(f"Error: {status_code}")
        
        return # For all cases except status_code == 200, function returns None
```

```{python}
#| label: lst-extract-metadata
#| lst-cap: "Function for extracting and joining metadata information."
#| code-fold: true
#| code-summary: "Click to see extract_join_metadata function."

def extract_join_metadata(data_dict, metadata_key, subkey=None):
    """
    Extract values from a metadata dictionary and join them into a string.

    Parameters
    ----------
    data_dict : dict
        Dictionary containing the metadata entries.
    metadata_key : str
        Key in `data_dict` whose value should be a list.
    subkey : str, optional
        Key to use within each list element.  
        If `None` the list elements are used directly.

    Returns
    -------
    str
        Comma-separated string of extracted values.
        "N/A"` if the list is empty or no values were found.
    """
    # Retrieve the list of items associated with metadata_key
    items = data_dict.get(metadata_key, []) # default to an empty list if not found

    extracted_items = [] # empty list

    if subkey: # In case there is a subkey
        for item in items: # Iterate through items
            # Get the value for the specific subkey
            value = item.get(subkey) # NO second arg to avoid list of "N/A"
            if value: 
                # If there is a value, it is added to the list
                extracted_items.append(value)
   
    # Return a string (comma-separated) if data was found 
    if extracted_items:
        return ", ".join(extracted_items) 
    else: # Otherwise, return "N/A"
        return "N/A" 
```

```{python}
#| label: lst-get-metadata
#| lst-cap: "Function for getting the metadata information."
#| code-fold: true
#| code-summary: "Click to see get_metadata_info function."

def get_metadata_info(pdb_id, filename=None):
    """
    Parse a PDB (Protein Data Bank) file and extract metadata information.
    Extracts and formats some metadata via extract_join_metadata function.
    Handles API errors via handle_API_error function.
    Stores the results in a pandas DataFrame.
    If a path is provided, writes it to a CSV file.
    
    Parameters
    ----------
    pdb_id : str
        Unique identifier for the PDB file.
    filename : str, optional
        The output CSV file path where metadata will be saved.
    
    Returns
    -------
    df : pd.DataFrame
        A pandas DataFrame containing the metadata.
        Or None if an error occurs.
    """
    # Define endpoints for RCSB PDB Data API 
    # Entry API: Global metadata -> PDB ID; Determination Method; Authors; 
    #                               Release Date; Resolution; Number of peptide chains; 
    #                               Number of Other molecules
    url_entry = f"https://data.rcsb.org/rest/v1/core/entry/{pdb_id}"

    # Entity API: Specific data for cheminal entities
    entity_id = 1 # Using 1 for the primary polymer (protein)
    url_entity = f"https://data.rcsb.org/rest/v1/core/polymer_entity/{pdb_id}/{entity_id}" 

    # Handling with Timeout and Errors (only two possibilities: 200 / 404)
    try:
        response_entry = requests.get(url_entry,
                                     timeout = 100) 
        response_entity = requests.get(url_entity,
                                      timeout = 100) 

    except requests.exceptions.Timeout: # Handling Timeout Error
        handle_API_error(pdb_id, flag_timeout = True)
        return
    
    # Validate that PDB ID exists in both endopoints
    flag_entry = handle_API_error(pdb_id, status_code = response_entry.status_code)
    flag_entity = handle_API_error(pdb_id, status_code = response_entity.status_code)

    if not flag_entry or not flag_entity:
        return
    
    # Execution continues only if a 200 OK status is received
    
    # Parse JSON responses
    data_entry = response_entry.json()
    data_entity = response_entity.json()

    ############ Metadata extraction ############

    # ---- PDB ID
    id = data_entry.get("rcsb_id", "N/A") # Default to "N/A" if rcsb_id is not found

    # ---- Protein name
    # Default to empty dict to safely chain subsequent .get() calls
    polymer_entity = data_entity.get("rcsb_polymer_entity", {}) 
    prot_name = polymer_entity.get("pdbx_description", "N/A") 
    
    # ---- Source Organism
    # Extract and format via extract_join_metadata
    source_organisms = extract_join_metadata(data_entity,
                                            "rcsb_entity_source_organism", 
                                            subkey="ncbi_scientific_name") 

    # ---- Determination Method
    det_method = extract_join_metadata(data_entry, 
                                      "exptl", 
                                      subkey="method")

    # ---- Authors
    primary_cit = data_entry.get("rcsb_primary_citation", {}) 
    authors = extract_join_metadata(data_entry, 
                                   "rcsb_authors") 

    # ---- Release date
    acc_info = data_entry.get("rcsb_accession_info", {}) 
    date = acc_info.get("initial_release_date", "N/A")

    # ---- Resolution
    entry_info = data_entry.get("rcsb_entry_info", {}) 
    resolution = entry_info.get("resolution_combined", []) 
    if resolution: # If resolution is not an empty list
        resolution = resolution[0] # To remove "[]" 
    else:
        resolution = "N/A"

    # ---- Number of peptide chains
    num_chains = entry_info.get("polymer_entity_count_protein", "N/A")

    # ---- Other molecules
    molecules = entry_info.get("nonpolymer_entity_count", "N/A")

    ############ Metadata dictionary ############

    # Assemble the metadata dictionary
    metadata = {
        "PDB ID": id,
        "Protein Name": prot_name,
        "Source Organims": source_organisms,
        "Determination Method": det_method,
        "Authors": authors,
        "Release Date": date,
        "Resolution": resolution,
        "Number of Peptide Chains": num_chains,
        "Number of Other Molecules": molecules
    }
    # Pass as a list to avoid "Scalar values" index error in Pandas
    df = pd.DataFrame([metadata])

    if filename:
        # Export the DataFrame to a CSV file
        df.to_csv(f"{filename}.csv", index=False) # index=False to prevent writing row numbers
        print(f"Metadata for {pdb_id} successfully saved to {filename}.csv")

    return metadata
```

## Structural Infrormation Extraction and Distance Matrix Calculation

To understand how a protein folds and how its redidues interact with each other, we first need to extract the spatial coordinates of the amino acids. This allows us to calculate the pairwise distances between them.

PDB stablished a standardized, human-readable text format to store the 3D structures of biomolecules. Each line in a PDB file corresponds to a specific type of record, utilizing fixed-width columns. The file begins with a header section, which contains general information about the structure, such as the PDB ID, protein name, realesed date, etc. This is followed by the atomic coordinates section, where each line corresponds to an atom in the structure and contains information about its type, residue, chain, and 3D coordinates (x, y, z). Those lines start with the keyword "ATOM". Finally, there is a connectivity section that describes how these atoms are bonded to form the overall structure of the molecule.

To extract the mentioned data, we have implemented the function @lst-get-structural-info, which make a request to the RCSB PDB API to obtain raw textual data of the PDB file. It then parses the response to extract the atomic coordinates of the C$\alpha$ atoms, which are commonly used to represent the backbone of the protein structure. 

The function also, translates the three-letter amino acid codes into one-letter codes using a mapping dictionary. Finally, it extracts the chain identifier, residue number and the cartesian coordinates (x, y, z), returning a structured dataframe that will be used for subsequent distance and contact map calculations.

To understand a protein's three-dimensional structure, we must measure the distances between its different parts. A Distance Matrix is a useful tool for this, providing a complete view of how every pair of residues in the structure is positioned. By calculating these distances, we can identify secondary structural elements and determine the tertiary or quaternary folding patterns that are crucial for the protein's biological function.

Mathematically, since each amino acid is represented by the Cartesian coordinates $(x, y, z)$ of its alpha carbon ($C\alpha$), the distance $d$ between two residues $i$ and $j$ is calculated using the three-dimensional *Euclidean distance formula*:
$$d_{ij} = \sqrt{(x_i - x_j)^2 + (y_i - y_j)^2 + (z_i - z_j)^2}$$

As a result, the matrix is square and symmetric, with diagonal elements always being zero, because they represent the distance of a residue to itself. Values close to the diagonal typically represent local interactions, while values far from the diagonal indicate long-range contacts between residues that are distant in the linear sequence but close in 3D space. 

To compute this, we implemented the @lst-distance-matrix, which extracts the $(x, y, z)$ coordinates as a NumPy array for optimized access. Using a nested loop structure, it iterates through every possible pair of atoms, calculating the differences in each spatial dimension, with the result in Angstroms (Å).


### Code Implementation
```{python}
#| label: lst-get-structural-info
#| lst-cap: "Function for getting the structural information."
#| code-fold: true
#| code-summary: "Click to see get_structural_info function."

def get_structural_info(pdb_id, flag_assembly=False, filename=None):
    """
    Retrieve and parse structural information from a PDB (Protein Data Bank) file.
    Extracts backbone data by filtering for Alpha Carbon atoms, as a simplified representation of the protein structure.
    Structural information extracted: chain, residue number, amino acid, 
    and cartesian coordinates (x, y, z).
    Handles API errors via handle_API_error function.
    
    Parameters
    ----------
    pdb_id : str
        Unique identifier for the PDB file.
    flag_assembly : bool, optional
        If true, enables parsing for biological assembly files to handle multimeric structures.
    filename : str, optional
        The output CSV file path where metadata will be saved.

    Returns
    -------
    results_df : pd.DataFrame
        A DataFrame containing structural information with columns:
        - chain: Protein chain identifier
        - residue_number: Sequence number of the residue
        - amino_acid: Single-letter amino acid code
        - x, y, z: Cartesian coordinates of the alpha carbon atom
    
        Returns None if the request fails due to timeout or HTTP error.
    """
    if flag_assembly: # Define the download endpoint for the biological assembly file
        url = f"https://files.rcsb.org/download/{pdb_id}.pdb1"
    else: # Define the download endpoint for the raw PDB file
        url = f"https://files.rcsb.org/download/{pdb_id}.pdb"
    
    # Handling with Timeout and Errors 
    try:
        response = requests.get(url, 
                               timeout = 100)
    
    except requests.exceptions.Timeout: # Handling Timeout Error
        handle_API_error(pdb_id, flag_timeout = True)
        return

    # Handle HTTP status code with handle_API_error and check if the request was successful
    flag = handle_API_error(pdb_id, status_code = response.status_code)
    
    if not flag:  # Proceed only if the request was successful (flag: True)
        return

    # Execution continues only if a 200 OK status is received

    # Mapping for 3-letter to 1-letter amino acid codes
    aa_map = {
        "ALA": "A", "ARG": "R", "ASN": "N", "ASP": "D", "CYS": "C", "GLN": "Q", "GLU": "E", 
        "GLY": "G", "HIS": "H", "ILE": "I", "LEU": "L", "LYS": "K", "MET": "M", "PHE": "F", 
        "PRO": "P", "SER": "S", "THR": "T", "TRP": "W", "TYR": "Y", "VAL": "V"
    }

    # Access the raw text content of the PDB file
    pdb_data = response.text # .text because is a .pdb file

    ############ Structural data extraction ############

    results = [] # List to store extracted structural data
    current_model = 0 # If there is more than one model in the .pdb1 file
    for line in pdb_data.split("\n"): # Parse .pdb file line by line
        
        if flag_assembly:
            if line.startswith("MODEL"): # Biological units are separated by "MODEL" records
                try:
                    # Extract the model number (columns 11-14)
                    current_model = int(line[10:14].strip()) 
                except: # Keep previous model index if parsing fails
                    pass

        if line.startswith("ATOM"): # Processing only atom lines
            # The PDB format uses fixed-width columns rather than delimiters (tabs/spaces)
            # Extract atom name (columns 13-16)
            atom_name = line[12:16].strip() # .strip() to remove blank spaces

            # Filter for Alpha Carbons (CA) to represent the protein backbone
            if atom_name == "CA": 
                # Extract 3-letter amino acid name (columns 18-20)
                aa_name = line[17:20].strip() 
                # Convert 3-letter to 1-letter using aa_map dictionary
                aa_name_1 = aa_map.get(aa_name, "X") # "X" for non-canonical residues

                # Extract XYZ coordinates from their fixed positions
                coord_x = line[30:38].strip() # X (columns 31-38)
                coord_y = line[38:46].strip() # Y (columns 39-46)
                coord_z = line[46:54].strip() # Z (columns 47-54)
                
                # Extract chain identifier (column 22)
                chain = line[21:22].strip()

                if current_model > 1:
                    # Create a unique ID for repeated chains in the assembly
                    unique_chain = f"{chain}_{current_model}"
                else:  # Keep original chain ID for the first model
                    unique_chain = chain

                # Extract residue sequence number (columns 23-26)
                residue_number = line[22:26].strip() 
                
                # Append record to the results list
                results.append({
                               "chain": unique_chain,
                               "residue_number": residue_number,
                               "amino_acid": aa_name_1,
                               "x": float(coord_x),
                               "y": float(coord_y),
                               "z": float(coord_z)
                            })
    
    # Transform data into a df
    results_df = pd.DataFrame(results)

    if filename:
        # Export the DataFrame to a CSV file
        results_df.to_csv(f"{filename}.csv", index=False) # index=False to prevent writing row numbers
        print(f"Structural data for {pdb_id} successfully saved to {filename}.csv")

    return results_df
```

```{python}
#| label: lst-distance-matrix
#| lst-cap: "Function for calculating the distance matrix."
#| code-fold: true
#| code-summary: "Click to see distance_matrix function."

def distance_matrix(df_structural_info):
    """
    Calculate the Euclidean distance matrix between all alpha carbon (CA) atoms in a protein structure.

    Parameters
    ----------
    df_structural_info : pandas.DataFrame
        A dataframe containing structural information with columns:
                chain / residue_number / amino_acid / x / y / z
    Returns
    -------
    distance_matrix : numpy.ndarray
        A square symmetric matrix of shape (n, n) where n is the number of CA atoms.
        Each element [i, j] contains the Euclidean distance between CA atoms i and j in angstroms.
        Diagonal elements are zero.
    """
    # Matrix size corresponds to the number of residues/atoms
    size = len(df_structural_info) 
    # Initialize a square matrix of zeros
    distance_matrix = np.zeros((size, size)) 

    # Extract xyz coordinates as a NumPy array (each row is [x, y, z])
    coordinates = df_structural_info[["x","y","z"]].values 

    # Iterate through each pair of coordinates to calculate distances
    for row, coord1 in enumerate(coordinates): # Reference coordinate
        for column, coord2 in enumerate(coordinates): # Comparison coordinate

            # Calculate the difference in each dimension
            dx = coord2[0] - coord1[0]
            dy = coord2[1] - coord1[1]
            dz = coord2[2] - coord1[2]

            # Apply the 3D distance formula: sqrt(dx^2 + dy^2 + dz^2)
            distance = math.sqrt(math.pow(dx, 2) + math.pow(dy, 2) + math.pow(dz, 2))

            # Store the result in the corresponding matrix cell
            distance_matrix[row,column] = distance 

    return distance_matrix
```


## Contact Map Calculation

In proteins, there can be both intrachain and interchain contacts, taking that into account, @lst-contact-matrix function was implemented to generate the corresponding matrices from the pairwise Cα distance matrix and residue chain information. 

Contacts were defined using a specific distance threshold, set by default between 6 Å and 12 Å. Distances below 6 Å are excluded to avoid trivial sequential contacts (immediate neighbors along the backbone), while distance above 12 Å are generally too far for meaningful non-covalent interactions. This range captures the most relevant spatial interactions associated with protein folding and function.

To visualize the computed contact matrices of each protein @lst-contact-map function was developed to generate contact maps differentiating between intrachain and interchain interactions, represented in green and red, respectively, which makes it easier the identification of oligomers.

### Code Implementation

```{python}
#| label: lst-contact-matrix
#| lst-cap: "Function for calculating the contact matrices."
#| code-fold: true
#| code-summary: "Click to see contact_matrix function."

def contact_matrix(structural_info, distance_matrix, min_distance=6, max_distance=12):
    """
    Generate intrachain and interchain contact matrices based on distance thresholds.

    Parameters
    ----------
    structural_info : pd.DataFrame
        DataFrame containing structural information with at least a "chain" column.
    distance_matrix : np.ndarray
        Matrix of pairwise distances between residues.
    min_distance : int
        Minimum distance threshold in Angstroms (default: 6).
    max_distance : int
        Maximum distance threshold in Angstroms (default: 12).

    Returns
    -------
    tuple 
        matrix_intra : np.ndarray
            2D contact matrix containing distances for intrachain contacts.
            Non-contact positions are NaN.
        matrix_inter : np.ndarray
            2D contact matrix containing distances for interchain contacts.
            Non-contact positions are NaN.
    """
    # Extract chain identifiers for each residue as a NumPy array
    chain_per_res = structural_info["chain"].values

    # Initialize contact matrices with NaNs (to prevent plotting non-relevant points)
    matrix_intra = np.full_like(distance_matrix, np.nan) # intrachain contacts
    matrix_inter = np.full_like(distance_matrix, np.nan)# interchain contacts

    # Define significant folding distances:
    # Default threshold [6, 12] avoids:
    # >6: immediate neighbors (useless for folding info)
    # <12: atoms that are too far apart  
    distance_bool_matrix = (distance_matrix >= min_distance) & (distance_matrix <= max_distance)

    # Boolean matrix where [i, j] is True if residue i and j belong to the same chain
    same_chain_bool_matrix = np.equal.outer(chain_per_res, chain_per_res) 

    # Intrachain contacts matrix. Must meet:
    # distance criteria (distance_bool_matrix)
    # AND both residues must belong to the same chain (same_chain_bool_matrix)
    matrix_intra[distance_bool_matrix & same_chain_bool_matrix] = distance_matrix[distance_bool_matrix & same_chain_bool_matrix]

    # Interchain contacts matrix. Must meet:
    # distance criteria (distance_bool_matrix)
    # AND both residues must belong to the different chains (~same_chain_bool_matrix)
    matrix_inter[distance_bool_matrix & ~same_chain_bool_matrix] = distance_matrix[distance_bool_matrix & ~same_chain_bool_matrix] 

    return matrix_intra, matrix_inter
```

```{python}
#| label: lst-contact-map
#| lst-cap: "Function for plotting the contact map."
#| code-fold: true
#| code-summary: "Click to see plot_contact_map."

def plot_contact_map (structural_info, intrachain_matrix, interchain_matrix, chains=None, pdb_id="-", filename=None):
    """
    falta docstring
    """
    if chains:
        # Check if all requested chains are present in the structural information
        available_chains = structural_info["chain"].unique()
        for chain in chains:
            if chain not in available_chains:
                print(f"One or more requested chains are not present.")
                return
            
        # Filter the structural info and get the indices of the rows we keep
        # This is crucial to also slice the matrices correctly later if they don't match
        chains_requested_bool_matrix = structural_info["chain"].isin(chains)
        structural_info = structural_info[chains_requested_bool_matrix]
                
        indices = np.where(chains_requested_bool_matrix)[0]
        intrachain_matrix = intrachain_matrix[np.ix_(indices, indices)]
        interchain_matrix = interchain_matrix[np.ix_(indices, indices)]
        
    # Extract chain identifiers for each residue as a NumPy array
    chain_per_res = structural_info["chain"].values
    
    plt.figure(figsize=(10, 12)) # Size of the plot

    # Plot Intra-chain contacts in Green       
    plt.imshow(intrachain_matrix, 
              cmap="Greens_r", # Sets the color palette to Reversed Greens
              interpolation="none", # Prevents blurring; each pixel represents exactly one residue
              origin="lower") # Places the (0,0) index at the bottom-left corner

    # Plot Inter-chain contacts in Green
    # Since contact matrices contain NaNs, the second plot won't overwrite the first
    plt.imshow(interchain_matrix, 
              cmap="Reds_r", 
              interpolation="none", 
              origin="lower")
    
    # Manually creating patches for the legend
    green_patch = mpatches.Patch(color="green", 
                                label="Intra-chain contact") 
    red_patch = mpatches.Patch(color="red", 
                              label="Inter-chain contact")
    patches = [green_patch, red_patch]
    
    # Adding legend
    plt.legend(handles=patches, # Text of the legend
              loc="upper right", # Place of the legend
              bbox_to_anchor=(1.35, 1)) # bbox_to_anchor places legend outside the plot area
 
    # Title and labels
    plt.title(f"CONTACT MAP (Protein: {pdb_id})", fontsize=14)
    plt.xlabel("Residue Index", fontsize=12)
    plt.ylabel("Residue Index", fontsize=12)
    
    # Identify indices where the chain ID changes by comparing current to next element
    idx_changes = np.where(chain_per_res[:-1] != chain_per_res[1:])[0] 
    # List of the start and end points for every chain
    boundaries = [0] + list(idx_changes + 0.5) + [len(chain_per_res)]

    # Unique chain names in order of appearance
    unique_chains = []
    unique_chains_label = []
    for each_chain in chain_per_res:
        if each_chain not in unique_chains: 
            unique_chains.append(each_chain)
            unique_chains_label.append(f"Chain {each_chain}") # Create labels to plot them
    
    # Draw lines to visually separate the different chains in the matrix
    for idx in idx_changes:
        # Add 0.5 to place the line exactly between the pixels of two residues
        plt.axhline(y=idx + 0.5, color="black", linestyle="--")
        plt.axvline(x=idx + 0.5, color='black', linestyle="--")
    
    # Place the labels of the chain names at the midpoint of each boundary
    ticks = []
    for i in range(len(boundaries) - 1):
        midpoint = (boundaries[i] + boundaries[i+1]) / 2 # Calculate the midpoint of each chain segment
        ticks.append(midpoint) # Appends ticks

    # Set up secondary axes to display chain labels
    axes = plt.gca() # Grabs the active plot area
    sec_xaxis= axes.secondary_xaxis("top") # Attaches a new axis to the top of that area
    sec_yaxis = axes.secondary_yaxis("right") # Attaches a new axis to the right of that area

    # Assign chain names to the secondary ticks
    sec_xaxis.set_xticks(ticks)
    sec_xaxis.set_xticklabels(unique_chains_label, fontsize=10)
    
    sec_yaxis.set_yticks(ticks)
    sec_yaxis.set_yticklabels(unique_chains_label, fontsize=10)

    plt.tight_layout() # Ensures labels/legend don't get cut off

    if filename: # Check if a filename was provided to save the image
        # Save the figure as a PNG file
        plt.savefig(f"{filename}.png", 
                    dpi=300, # dpi=300 ensures high resolution
                    bbox_inches="tight") # bbox_inches="tight" prevents labels from being cut off
        print(f"Contact plot for {pdb_id} successfully saved to {filename}.png")

    plt.show()
```

---

# Results

TABLA CON LOS RESULTADOS DE LAS DISTANCIAS Y CONTACTOS


---

# Discussion

## `1RBP`

{{< mol-rcsb 1RBP viewportShowAnimation=false >}}

## `1QRE`

{{< mol-rcsb 1QRE viewportShowAnimation=false >}}

## `1DGF`

{{< mol-rcsb 1DGF viewportShowAnimation=false >}}

---

# Conclusion

---

# Annexes

## Work Register

The development of this project has followed a workflow managed via GitHub, in order it can be reproduced.

The following table sumarizes the main stages of the project.

```{python}
#| echo: false
table_github = pd.DataFrame({
    "Phase": [
        "Setup", 
        "Metadata", 
        "Protein structural information", 
        "Distance matrix", 
        "Contact maps", 
        "Report writing"], 
    "Description":[
        "Repository initialization and project structuring", 
        "Access to each protein key information via APIs and store it in a dataframe", 
        "Get access to PDB files and parse them to gen atomic coordinates",
        "Compute the distances matrix between Cα atoms",
        "Plot intra/interchain contacts giving a threshold",
        "Create the final file and include all the previous analysis"]})
table_github
```

Every modification is documented through a descriptive commit message.

**Repository Access**: https://github.com/MCML-Projects/STRBIO.git 
