---
title: "Parsing Function"
format: html
---
1. Write a function that parses the files and generate a table or report with metadata and key information from the structures, including PDB ID, protein name, source organism, determination method, authors, release date, resolution, and the number of peptide chains and other molecules.
Tip
You may find some amino acids that are not canonical. If so, you can either change to the canonical one or use X in the fasta sequence.


Para encontrar el API de RCSB PDB, he seguido este link: https://data.rcsb.org/redoc/index.html


he añadido otro link de:
- entry
- entity
(explicaría en el texto la diferencia de datos o de archivos de cada uno, ya que no vienen todos los datos en uno directamente)
He hecho este códgio de abajo basado en lo de Lucía de arriba:

aun así, para la entrega yo no pondría los códigos de dentro del diccionario de metadata así, sino que lo expandiría un poco más (igual extraer todo por separado con más pasos y luego meterlo en metadata?) para que quede algo más claro

```{python}
#| label: setup-libraries
#| message: false
#| warning: false

import requests
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches 

```

DUDA: me pone en la web que puso lucía que las posibles salidas son directamente:
200 o 404, eso es que no puede haber más?

```{python}
#| label: extract_join_metadata_function
def extract_join_metadata(data_dict, metadata_key, subkey=None):
    """
    Extract values from a metadata dictionary and join them into a string.

    Parameters
    ----------
    data_dict : dict
        Dictionary containing the metadata entries.
    metadata_key : str
        Key in `data_dict` whose value should be a list.
    subkey : str, optional
        Key to use within each list element.  
        If `None` the list elements are used directly.

    Returns
    -------
    str
        Comma-separated string of extracted values.
        "N/A"` if the list is empty or no values were found.
    """
    # Retrieve the list of items associated with metadata_key
    items = data_dict.get(metadata_key, []) # default to an empty list if not found

    extracted_items = [] # empty list

    if subkey: # In case there is a subkey
        for item in items: # Iterate through items
            # Get the value for the specific subkey
            value = item.get(subkey) # NO second arg to avoid list of "N/A"
            if value: 
                # If there is a value, it is added to the list
                extracted_items.append(value)
   
    # Return a string (comma-separated) if data was found 
    if extracted_items:
        return ", ".join(extracted_items) 
    else: # Otherwise, return "N/A"
        return "N/A" 
```


```{python}
#| label: handle_API_error_function

def handle_API_error(id, status_code = None, flag_timeout = False):
    """
    Handles HTTP request errors or timeouts and prints informative messages in
    order to centralize the management of API request errors.

    Parameters
    ----------
    id : str
        PDB ID queried in the request.
    status_code : int
        HTTP status code returned by the request. 
        None by default (in case of timeout error).
    flag_timeout : bool
        Indicates whether the request failed due to a timeout.
        If True, the status_code is ignored.
        alse by default.

    Returns
    -------
        bool (True)
            True if the request was successful (status code 200).
            None returned for any error or timeout condition.
    """
    if flag_timeout: # If a timeout occurred, skip all other checks
        print(f"[408] Timeout error for ID: {id}.")
        
    else:
        if status_code == 200: # If the request was successful, returns True
            return True
        
        elif status_code == 301 or status_code == 302:
            # Resource has been permanently or temporarily moved
            print(f"[301] or [302] The object was moved to other route")

        elif status_code == 400:
            # Request processed but considered unsuccessful
            print(f"[400] Not valid ID: {id}")

        elif status_code == 404:
            # Request processed but no result was obtained
            print(f"[404] Result not found for ID: {id}")

        elif status_code == 429:
            # Request rejected due to request rate limits
            print(f"[429] Error: Too many requests.")

        elif status_code == 500 or status_code == 503:
            # Request failed due to internal server issues
            print("[500] or [503] Internal Server Error")

        else: # For any other error status code
            print(f"Error: {status_code}")
        
        return # For all cases except status_code == 200, function returns None
```

```{python}
#| label: get_metadata_info_function

def get_metadata_info(pdb_id, filename=None):
    """
    Parse a PDB (Protein Data Bank) file and extract metadata information.
    Extracts and formats some metadata via extract_join_metadata function.
    Handles API errors via handle_API_error function.
    Stores the results in a pandas DataFrame.
    If a path is provided, writes it to a CSV file.
    
    Parameters
    ----------
    pdb_id : str
        Unique identifier for the PDB file.
    filename : str, optional
        The output CSV file path where metadata will be saved.
    
    Returns
    -------
    df : pd.DataFrame
        A pandas DataFrame containing the metadata.
        Or None if an error occurs.
    """
    # Define endpoints for RCSB PDB Data API 
    # Entry API: Global metadata -> PDB ID; Determination Method; Authors; 
    #                               Release Date; Resolution; Number of peptide chains; 
    #                               Number of Other molecules
    url_entry = f"https://data.rcsb.org/rest/v1/core/entry/{pdb_id}"

    # Entity API: Specific data for cheminal entities
    entity_id = 1 # Using 1 for the primary polymer (protein)
    url_entity = f"https://data.rcsb.org/rest/v1/core/polymer_entity/{pdb_id}/{entity_id}" 

    # Handling with Timeout and Errors (only two possibilities: 200 / 404)
    try:
        response_entry = requests.get(url_entry,
                                     timeout = 100) 
        response_entity = requests.get(url_entity,
                                      timeout = 100) 

    except requests.exceptions.Timeout: # Handling Timeout Error
        handle_API_error(pdb_id, flag_timeout = True)
        return
    
    # Validate that PDB ID exists in both endopoints
    flag_entry = handle_API_error(pdb_id, status_code = response_entry.status_code)
    flag_entity = handle_API_error(pdb_id, status_code = response_entity.status_code)

    if not flag_entry or not flag_entity:
        return
    
    # Execution continues only if a 200 OK status is received
    
    # Parse JSON responses
    data_entry = response_entry.json()
    data_entity = response_entity.json()

    ############ Metadata extraction ############

    # ---- PDB ID
    id = data_entry.get("rcsb_id", "N/A") # Default to "N/A" if rcsb_id is not found

    # ---- Protein name
    # Default to empty dict to safely chain subsequent .get() calls
    polymer_entity = data_entity.get("rcsb_polymer_entity", {}) 
    prot_name = polymer_entity.get("pdbx_description", "N/A") 
    
    # ---- Source Organism
    # Extract and format via extract_join_metadata
    source_organisms = extract_join_metadata(data_entity,
                                            "rcsb_entity_source_organism", 
                                            subkey="ncbi_scientific_name") 

    # ---- Determination Method
    det_method = extract_join_metadata(data_entry, 
                                      "exptl", 
                                      subkey="method")

    # ---- Authors
    primary_cit = data_entry.get("rcsb_primary_citation", {}) 
    authors = extract_join_metadata(data_entry, 
                                   "rcsb_authors") 

    # ---- Release date
    acc_info = data_entry.get("rcsb_accession_info", {}) 
    date = acc_info.get("initial_release_date", "N/A")

    # ---- Resolution
    entry_info = data_entry.get("rcsb_entry_info", {}) 
    resolution = entry_info.get("resolution_combined", []) 
    if resolution: # If resolution is not an empty list
        resolution = resolution[0] # To remove "[]" 
    else:
        resolution = "N/A"

    # ---- Number of peptide chains
    num_chains = entry_info.get("polymer_entity_count_protein", "N/A")

    # ---- Other molecules
    molecules = entry_info.get("nonpolymer_entity_count", "N/A")

    ############ Metadata dictionary ############

    # Assemble the metadata dictionary
    metadata = {
        "PDB ID": id,
        "Protein Name": prot_name,
        "Source Organims": source_organisms,
        "Determination Method": det_method,
        "Authors": authors,
        "Release Date": date,
        "Resolution": resolution,
        "Number of Peptide Chains": num_chains,
        "Number of Other Molecules": molecules
    }
    # Pass as a list to avoid "Scalar values" index error in Pandas
    df = pd.DataFrame([metadata])

    if filename:
        # Export the DataFrame to a CSV file
        df.to_csv(f"{filename}.csv", index=False) # index=False to prevent writing row numbers
        print(f"Metadata for {pdb_id} successfully saved to {filename}.csv")

    return metadata
```


2. Parse the data to extract the protein structural information from the PDB file in tabular format, then compute the pairwise distance matrix for each PDB structure. The distance between two amino acids is usually calculated as the 3D Euclidean distance between their C-alpha (CA) atoms.


```{python}
#| label: get_structural_info_function

def get_structural_info(pdb_id, flag_assembly=False, filename=None):
    """
    Retrieve and parse structural information from a PDB (Protein Data Bank) file.
    Extracts backbone data by filtering for Alpha Carbon atoms, as a simplified representation of the protein structure.
    Structural information extracted: chain, residue number, amino acid, 
    and cartesian coordinates (x, y, z).
    Handles API errors via handle_API_error function.
    
    Parameters
    ----------
    pdb_id : str
        Unique identifier for the PDB file.
    flag_assembly : bool, optional
        If true, enables parsing for biological assembly files to handle multimeric structures.
    filename : str, optional
        The output CSV file path where metadata will be saved.

    Returns
    -------
    results_df : pd.DataFrame
        A DataFrame containing structural information with columns:
        - chain: Protein chain identifier
        - residue_number: Sequence number of the residue
        - amino_acid: Single-letter amino acid code
        - x, y, z: Cartesian coordinates of the alpha carbon atom
    
        Returns None if the request fails due to timeout or HTTP error.
    """
    if flag_assembly: # Define the download endpoint for the biological assembly file
        url = f"https://files.rcsb.org/download/{pdb_id}.pdb1"
    else: # Define the download endpoint for the raw PDB file
        url = f"https://files.rcsb.org/download/{pdb_id}.pdb"
    
    # Handling with Timeout and Errors 
    try:
        response = requests.get(url, 
                               timeout = 100)
    
    except requests.exceptions.Timeout: # Handling Timeout Error
        handle_API_error(pdb_id, flag_timeout = True)
        return

    # Handle HTTP status code with handle_API_error and check if the request was successful
    flag = handle_API_error(pdb_id, status_code = response.status_code)
    
    if not flag:  # Proceed only if the request was successful (flag: True)
        return

    # Execution continues only if a 200 OK status is received

    # Mapping for 3-letter to 1-letter amino acid codes
    aa_map = {
        "ALA": "A", "ARG": "R", "ASN": "N", "ASP": "D", "CYS": "C", "GLN": "Q", "GLU": "E", 
        "GLY": "G", "HIS": "H", "ILE": "I", "LEU": "L", "LYS": "K", "MET": "M", "PHE": "F", 
        "PRO": "P", "SER": "S", "THR": "T", "TRP": "W", "TYR": "Y", "VAL": "V"
    }

    # Access the raw text content of the PDB file
    pdb_data = response.text # .text because is a .pdb file

    ############ Structural data extraction ############

    results = [] # List to store extracted structural data
    current_model = 0 # If there is more than one model in the .pdb1 file
    for line in pdb_data.split("\n"): # Parse .pdb file line by line
        
        if flag_assembly:
            if line.startswith("MODEL"): # Biological units are separated by "MODEL" records
                try:
                    # Extract the model number (columns 11-14)
                    current_model = int(line[10:14].strip()) 
                except: # Keep previous model index if parsing fails
                    pass

        if line.startswith("ATOM"): # Processing only atom lines
            # The PDB format uses fixed-width columns rather than delimiters (tabs/spaces)
            # Extract atom name (columns 13-16)
            atom_name = line[12:16].strip() # .strip() to remove blank spaces

            # Filter for Alpha Carbons (CA) to represent the protein backbone
            if atom_name == "CA": 
                # Extract 3-letter amino acid name (columns 18-20)
                aa_name = line[17:20].strip() 
                # Convert 3-letter to 1-letter using aa_map dictionary
                aa_name_1 = aa_map.get(aa_name, "X") # "X" for non-canonical residues

                # Extract XYZ coordinates from their fixed positions
                coord_x = line[30:38].strip() # X (columns 31-38)
                coord_y = line[38:46].strip() # Y (columns 39-46)
                coord_z = line[46:54].strip() # Z (columns 47-54)
                
                # Extract chain identifier (column 22)
                chain = line[21:22].strip()

                if current_model > 1:
                    # Create a unique ID for repeated chains in the assembly
                    unique_chain = f"{chain}_{current_model}"
                else:  # Keep original chain ID for the first model
                    unique_chain = chain

                # Extract residue sequence number (columns 23-26)
                residue_number = line[22:26].strip() 
                
                # Append record to the results list
                results.append({
                               "chain": unique_chain,
                               "residue_number": residue_number,
                               "amino_acid": aa_name_1,
                               "x": float(coord_x),
                               "y": float(coord_y),
                               "z": float(coord_z)
                            })
    
    # Transform data into a df
    results_df = pd.DataFrame(results)

    if filename:
        # Export the DataFrame to a CSV file
        results_df.to_csv(f"{filename}.csv", index=False) # index=False to prevent writing row numbers
        print(f"Structural data for {pdb_id} successfully saved to {filename}.csv")

    return results_df
```


justificacion de porqué hay que acceder así:
El formato PDB es un estándar de columnas fijas (basado en las antiguas tarjetas perforadas). Esto significa que no importa cuántos espacios haya; lo que importa es la posición exacta (el índice) de cada carácter en la línea.



Generamos la matriz de distancias

```{python}
#| label: distance_matrix_function

def distance_matrix(df_structural_info):
    """
    Calculate the Euclidean distance matrix between all alpha carbon (CA) atoms in a protein structure.

    Parameters
    ----------
    df_structural_info : pandas.DataFrame
        A dataframe containing structural information with columns:
                chain / residue_number / amino_acid / x / y / z
    Returns
    -------
    distance_matrix : numpy.ndarray
        A square symmetric matrix of shape (n, n) where n is the number of CA atoms.
        Each element [i, j] contains the Euclidean distance between CA atoms i and j in angstroms.
        Diagonal elements are zero.
    """
    # Matrix size corresponds to the number of residues/atoms
    size = len(df_structural_info) 
    # Initialize a square matrix of zeros
    distance_matrix = np.zeros((size, size)) 

    # Extract xyz coordinates as a NumPy array (each row is [x, y, z])
    coordinates = df_structural_info[["x","y","z"]].values 

    # Iterate through each pair of coordinates to calculate distances
    for row, coord1 in enumerate(coordinates): # Reference coordinate
        for column, coord2 in enumerate(coordinates): # Comparison coordinate

            # Calculate the difference in each dimension
            dx = coord2[0] - coord1[0]
            dy = coord2[1] - coord1[1]
            dz = coord2[2] - coord1[2]

            # Apply the 3D distance formula: sqrt(dx^2 + dy^2 + dz^2)
            distance = math.sqrt(math.pow(dx, 2) + math.pow(dy, 2) + math.pow(dz, 2))

            # Store the result in the corresponding matrix cell
            distance_matrix[row,column] = distance 

    return distance_matrix
```

3. Write a function for plotting the corresponding contact map for each structure, using a standard contact threshold (between 6-12 Å) and different colors for different contacts (intra- and interchain).

función para generar las matrices de contacto:
-intra e inter chain

```{python}
#| label: contact_matrix_function

def contact_matrix(structural_info, distance_matrix, min_distance=6, max_distance=12):
    """
    Generate intrachain and interchain contact matrices based on distance thresholds.

    Parameters
    ----------
    structural_info : pd.DataFrame
        DataFrame containing structural information with at least a "chain" column.
    distance_matrix : np.ndarray
        Matrix of pairwise distances between residues.
    min_distance : int
        Minimum distance threshold in Angstroms (default: 6).
    max_distance : int
        Maximum distance threshold in Angstroms (default: 12).

    Returns
    -------
    tuple 
        matrix_intra : np.ndarray
            2D contact matrix containing distances for intrachain contacts.
            Non-contact positions are NaN.
        matrix_inter : np.ndarray
            2D contact matrix containing distances for interchain contacts.
            Non-contact positions are NaN.
    """
    # Extract chain identifiers for each residue as a NumPy array
    chain_per_res = structural_info["chain"].values

    # Initialize contact matrices with NaNs (to prevent plotting non-relevant points)
    matrix_intra = np.full_like(distance_matrix, np.nan) # intrachain contacts
    matrix_inter = np.full_like(distance_matrix, np.nan)# interchain contacts

    # Define significant folding distances:
    # Default threshold [6, 12] avoids:
    # >6: immediate neighbors (useless for folding info)
    # <12: atoms that are too far apart  
    distance_bool_matrix = (distance_matrix >= min_distance) & (distance_matrix <= max_distance)

    # Boolean matrix where [i, j] is True if residue i and j belong to the same chain
    same_chain_bool_matrix = np.equal.outer(chain_per_res, chain_per_res) 

    # Intrachain contacts matrix. Must meet:
    # distance criteria (distance_bool_matrix)
    # AND both residues must belong to the same chain (same_chain_bool_matrix)
    matrix_intra[distance_bool_matrix & same_chain_bool_matrix] = distance_matrix[distance_bool_matrix & same_chain_bool_matrix]

    # Interchain contacts matrix. Must meet:
    # distance criteria (distance_bool_matrix)
    # AND both residues must belong to the different chains (~same_chain_bool_matrix)
    matrix_inter[distance_bool_matrix & ~same_chain_bool_matrix] = distance_matrix[distance_bool_matrix & ~same_chain_bool_matrix] 

    return matrix_intra, matrix_inter
```



FUNCION SEPARADA PARA PLOTEAR:
```{python}
#| label: plot_contact_matrix_function

def plot_contact_matrix (structural_info, intrachain_matrix, interchain_matrix, chains=None, pdb_id="-", filename=None):
    """
    falta docstring
    """
    if chains:
        # Check if all requested chains are present in the structural information
        available_chains = structural_info["chain"].unique()
        for chain in chains:
            if chain not in available_chains:
                print(f"One or more requested chains are not present.")
                return
            
        # Filter the structural info and get the indices of the rows we keep
        # This is crucial to also slice the matrices correctly later if they don't match
        chains_requested_bool_matrix = structural_info["chain"].isin(chains)
        structural_info = structural_info[chains_requested_bool_matrix]
                
        indices = np.where(chains_requested_bool_matrix)[0]
        intrachain_matrix = intrachain_matrix[np.ix_(indices, indices)]
        interchain_matrix = interchain_matrix[np.ix_(indices, indices)]
        
    # Extract chain identifiers for each residue as a NumPy array
    chain_per_res = structural_info["chain"].values
    
    plt.figure(figsize=(10, 12)) # Size of the plot

    # Plot Intra-chain contacts in Green       
    plt.imshow(intrachain_matrix, 
              cmap="Greens_r", # Sets the color palette to Reversed Greens
              interpolation="none", # Prevents blurring; each pixel represents exactly one residue
              origin="lower") # Places the (0,0) index at the bottom-left corner

    # Plot Inter-chain contacts in Green
    # Since contact matrices contain NaNs, the second plot won't overwrite the first
    plt.imshow(interchain_matrix, 
              cmap="Reds_r", 
              interpolation="none", 
              origin="lower")
    
    # Manually creating patches for the legend
    green_patch = mpatches.Patch(color="green", 
                                label="Intra-chain contact") 
    red_patch = mpatches.Patch(color="red", 
                              label="Inter-chain contact")
    patches = [green_patch, red_patch]
    
    # Adding legend
    plt.legend(handles=patches, # Text of the legend
              loc="upper right", # Place of the legend
              bbox_to_anchor=(1.35, 1)) # bbox_to_anchor places legend outside the plot area
 
    # Title and labels
    plt.title(f"CONTACT MAP (Protein: {pdb_id}) (6-12 Å)", fontsize=14)
    plt.xlabel("Residue Index", fontsize=12)
    plt.ylabel("Residue Index", fontsize=12)
    
    # Identify indices where the chain ID changes by comparing current to next element
    idx_changes = np.where(chain_per_res[:-1] != chain_per_res[1:])[0] 
    # List of the start and end points for every chain
    boundaries = [0] + list(idx_changes + 0.5) + [len(chain_per_res)]

    # Unique chain names in order of appearance
    unique_chains = []
    unique_chains_label = []
    for each_chain in chain_per_res:
        if each_chain not in unique_chains: 
            unique_chains.append(each_chain)
            unique_chains_label.append(f"Chain {each_chain}") # Create labels to plot them
    
    # Draw lines to visually separate the different chains in the matrix
    for idx in idx_changes:
        # Add 0.5 to place the line exactly between the pixels of two residues
        plt.axhline(y=idx + 0.5, color="black", linestyle="--")
        plt.axvline(x=idx + 0.5, color='black', linestyle="--")
    
    # Place the labels of the chain names at the midpoint of each boundary
    ticks = []
    for i in range(len(boundaries) - 1):
        midpoint = (boundaries[i] + boundaries[i+1]) / 2 # Calculate the midpoint of each chain segment
        ticks.append(midpoint) # Appends ticks

    # Set up secondary axes to display chain labels
    axes = plt.gca() # Grabs the active plot area
    sec_xaxis= axes.secondary_xaxis("top") # Attaches a new axis to the top of that area
    sec_yaxis = axes.secondary_yaxis("right") # Attaches a new axis to the right of that area

    # Assign chain names to the secondary ticks
    sec_xaxis.set_xticks(ticks)
    sec_xaxis.set_xticklabels(unique_chains_label, fontsize=10)
    
    sec_yaxis.set_yticks(ticks)
    sec_yaxis.set_yticklabels(unique_chains_label, fontsize=10)

    plt.tight_layout() # Ensures labels/legend don't get cut off

    if filename: # Check if a filename was provided to save the image
        # Save the figure as a PNG file
        plt.savefig(f"{filename}.png", 
                    dpi=300, # dpi=300 ensures high resolution
                    bbox_inches="tight") # bbox_inches="tight" prevents labels from being cut off
        print(f"Contact plot for {pdb_id} successfully saved to {filename}.png")

    plt.show()
```

4. Try to interpret the plots. Can you identify any structure in the contact maps? If so, which ones? Determine the type of structure as well (monomer,homo- or hetero- dimer, tetramer… ).


```{python}

pdb = "1DGF"
filename=rf"C:\Users\marta\Desktop\MÁSTER\STRBIO\Practica\{pdb}"
df_metadata = get_metadata_info(pdb, filename)
df_struct = get_structural_info(pdb)
# df_struct2 = get_structural_info(pdb, flag_assembly=True)
dist = distance_matrix(df_struct)
# dist2 = distance_matrix(df_struct2)

intra_contact, inter_contact = contact_matrix(df_struct, dist, min_distance=0)
# intra_contact2, inter_contact2 = contact_matrix(df_struct2, dist2, min_distance=0)

    #para plotear la matiz de contacto
plot_contact_matrix(df_struct, intra_contact, inter_contact, chains=["A","B"], pdb_id=pdb, filename=rf"C:\Users\marta\Desktop\MÁSTER\STRBIO\Practica\{pdb}")

plot_contact_matrix(df_struct, intra_contact, inter_contact, chains=["A"], pdb_id=pdb, filename=rf"C:\Users\marta\Desktop\MÁSTER\STRBIO\Practica\{pdb}")

plot_contact_matrix(df_struct, intra_contact, inter_contact, chains=["A","B","C"], pdb_id=pdb, filename=rf"C:\Users\marta\Desktop\MÁSTER\STRBIO\Practica\{pdb}")

plot_contact_matrix(df_struct, intra_contact, inter_contact, chains=["A","B","A"], pdb_id=pdb, filename=rf"C:\Users\marta\Desktop\MÁSTER\STRBIO\Practica\{pdb}")

plot_contact_matrix(df_struct, intra_contact, inter_contact, chains=["A","A"], pdb_id=pdb, filename=rf"C:\Users\marta\Desktop\MÁSTER\STRBIO\Practica\{pdb}")
# plot_contact_matrix(df_struct2, intra_contact2, inter_contact2, pdb, filename=rf"C:\Users\marta\Desktop\MÁSTER\STRBIO\Practica\CAMBIO{pdb}")
```


```{python}
#| include : false
pdb = "1QRE"
filename=rf"C:\Users\marta\Desktop\MÁSTER\STRBIO\Practica\{pdb}"
df_metadata = get_metadata_info(pdb, filename)
df_struct = get_structural_info(pdb)
df_struct2 = get_structural_info(pdb, flag_assembly=True)
dist = distance_matrix(df_struct)
dist2 = distance_matrix(df_struct2)

intra_contact, inter_contact = contact_matrix(df_struct, dist, min_distance=0)
intra_contact2, inter_contact2 = contact_matrix(df_struct2, dist2, min_distance=0)

    #para plotear la matiz de contacto
plot_contact_matrix(df_struct, intra_contact, inter_contact, pdb_id=pdb, filename=rf"C:\Users\marta\Desktop\MÁSTER\STRBIO\Practica\{pdb}")

plot_contact_matrix(df_struct2, intra_contact2, inter_contact2, pdb_id=pdb, filename=rf"C:\Users\marta\Desktop\MÁSTER\STRBIO\Practica\CAMBIO{pdb}")
```
## Para que funcione todo:

```{python}
#| include : false
#pdb_list = ["1RBP"]
pdb_list = ["1RBP", "1QRE", "1DGF"]
for id in pdb_list:
    ###ruta para guradar donde querais
    # hay qu eañadir la r para que cambie las \ a / (o cambiarlas a mano)
    filename=rf"C:\Users\marta\Desktop\MÁSTER\STRBIO\Practica\{id}"

    #dataframe con los metadatos -> df_metadata_info
    df_metadata_info = get_metadata_info(id, filename)

    #dataframe con la info estructural -> df_struct_info
    df_struct_info = get_structural_info(id)

    #matriz de distancias -> dist_matrix
    dist_matrix = distance_matrix(df_struct_info)

    #matriz de contacto: intracadena (intra_contact_matrix) e intercadena (inter_contact_matrix)
    intra_contact_matrix, inter_contact_matrix = contact_matrix(df_struct_info, dist_matrix, min_distance=0)

    #para plotear la matiz de contacto
    plot_contact_matrix(df_struct_info, intra_contact_matrix, inter_contact_matrix, pdb_id=id, filename=rf"C:\Users\marta\Desktop\MÁSTER\STRBIO\Practica\{id}")
    ###IDEA PODRÍAMOS GUARDAR LA IMAGEN EN UN .JPG EN EL DIRECTORIO!!!

```



